# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oplus/camera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/oplus/camera

PRODUCT_COPY_FILES += \
    vendor/oplus/camera/proprietary/system_ext/lib64/libAPSClient-cmd-jni.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libAPSClient-cmd-jni.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libAPSClient-jni.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libAPSClient-jni.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libAncFilter_jni.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libAncFilter_jni.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libAncHumBokeh-jni.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libAncHumBokeh-jni.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libAncHumanDoubleExposure-jni.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libAncHumanDoubleExposure-jni.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libAncHumanRetain-jni_v2.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libAncHumanRetain-jni_v2.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libAncHumanSegFigureFusion-jni.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libAncHumanSegFigureFusion-jni.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libAncHumanVideo-jni.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libAncHumanVideo-jni.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libApsFaceBeautyPreviewProductJni.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libApsFaceBeautyPreviewProductJni.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libAvatarEngineRender.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libAvatarEngineRender.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libAvatarEngineRenderNative.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libAvatarEngineRenderNative.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libCombineLut.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libCombineLut.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libCombineLutJni.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libCombineLutJni.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libFileExtender-jni.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libFileExtender-jni.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libOplusBlurPreviewJNI.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libOplusBlurPreviewJNI.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libSuperTextWrapper.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libSuperTextWrapper.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libXDocProcessSDK-jni.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libXDocProcessSDK-jni.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libXDocProcessSDK.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libXDocProcessSDK.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libYTCommon.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libYTCommon.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libarcsoft_wideselfie.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libarcsoft_wideselfie.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libcolorx-loader.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libcolorx-loader.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libcolorx.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libcolorx.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libcoolex.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libcoolex.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libextendfile.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libextendfile.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libjni_wideselfie.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libjni_wideselfie.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libjnisingleblur_api.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libjnisingleblur_api.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libjnistblur_api.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libjnistblur_api.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libmpbase.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libmpbase.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libsingle_camera_bokeh_native.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libsingle_camera_bokeh_native.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libst_mobile.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libst_mobile.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libst_sticker_jni.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libst_sticker_jni.so \
    vendor/oplus/camera/proprietary/system_ext/etc/default-permissions/oplus_camera_default_grant_permissions_list.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/default-permissions/oplus_camera_default_grant_permissions_list.xml \
    vendor/oplus/camera/proprietary/odm/lib64/libCaptureBokeh.so:$(TARGET_COPY_OUT_ODM)/lib64/libCaptureBokeh.so \
    vendor/oplus/camera/proprietary/odm/lib64/libOPAlgoCamAIBeautyBodyDetection.so:$(TARGET_COPY_OUT_ODM)/lib64/libOPAlgoCamAIBeautyBodyDetection.so \
    vendor/oplus/camera/proprietary/odm/lib64/libOPAlgoCamAiBeautyEyeRetouchCn.so:$(TARGET_COPY_OUT_ODM)/lib64/libOPAlgoCamAiBeautyEyeRetouchCn.so \
    vendor/oplus/camera/proprietary/odm/lib64/libOPAlgoCamAiBeautyFaceRetouchCn.so:$(TARGET_COPY_OUT_ODM)/lib64/libOPAlgoCamAiBeautyFaceRetouchCn.so \
    vendor/oplus/camera/proprietary/odm/lib64/libOPAlgoCamAiUnifySkin.so:$(TARGET_COPY_OUT_ODM)/lib64/libOPAlgoCamAiUnifySkin.so \
    vendor/oplus/camera/proprietary/odm/lib64/libOPAlgoCamFaceBeautyCap.so:$(TARGET_COPY_OUT_ODM)/lib64/libOPAlgoCamFaceBeautyCap.so \
    vendor/oplus/camera/proprietary/odm/lib64/libOPAlgoCamFaceRestore.so:$(TARGET_COPY_OUT_ODM)/lib64/libOPAlgoCamFaceRestore.so \
    vendor/oplus/camera/proprietary/odm/lib64/libOPAlgoCamHybridRaw.so:$(TARGET_COPY_OUT_ODM)/lib64/libOPAlgoCamHybridRaw.so \
    vendor/oplus/camera/proprietary/odm/lib64/libOPAlgoCamSinglePortrait.so:$(TARGET_COPY_OUT_ODM)/lib64/libOPAlgoCamSinglePortrait.so \
    vendor/oplus/camera/proprietary/odm/lib64/libXDocProcessSDK.so:$(TARGET_COPY_OUT_ODM)/lib64/libXDocProcessSDK.so \
    vendor/oplus/camera/proprietary/odm/lib64/libarcsoft_turbo_fusion_raw_portrait_super_night.so:$(TARGET_COPY_OUT_ODM)/lib64/libarcsoft_turbo_fusion_raw_portrait_super_night.so \
    vendor/oplus/camera/proprietary/odm/lib64/libarcsoft_turbo_fusion_raw_super_night.so:$(TARGET_COPY_OUT_ODM)/lib64/libarcsoft_turbo_fusion_raw_super_night.so \
    vendor/oplus/camera/proprietary/odm/lib64/libarcsoft_turbo_hdr_grf.so:$(TARGET_COPY_OUT_ODM)/lib64/libarcsoft_turbo_hdr_grf.so \
    vendor/oplus/camera/proprietary/odm/lib64/libarcsoft_turbo_hdr_raw.so:$(TARGET_COPY_OUT_ODM)/lib64/libarcsoft_turbo_hdr_raw.so \
    vendor/oplus/camera/proprietary/odm/lib64/libarcsoft_turbo_hdr_raw_front.so:$(TARGET_COPY_OUT_ODM)/lib64/libarcsoft_turbo_hdr_raw_front.so \
    vendor/oplus/camera/proprietary/odm/lib64/libarcsoft_turbo_raw.so:$(TARGET_COPY_OUT_ODM)/lib64/libarcsoft_turbo_raw.so \
    vendor/oplus/camera/proprietary/odm/lib64/libtrace.so:$(TARGET_COPY_OUT_ODM)/lib64/libtrace.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libHeifEncoderWrapper.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libHeifEncoderWrapper.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/libNativeWinBuffExchange.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libNativeWinBuffExchange.so \
    vendor/oplus/camera/proprietary/system_ext/lib64/liboplusheifwriter.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/liboplusheifwriter.so \
    vendor/oplus/camera/proprietary/vendor/lib64/libpenguin.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpenguin.so

PRODUCT_PACKAGES += \
    OplusAppPlatform \
    OplusCamera \
    oplus-support-wrapper \
    com.oplus.camera.unit.sdk.adapter \
    com.oplus.camera.unit.sdk
